# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0002_auto_20160822_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_to_user', to='book_review.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_to_book', to='book_review.Book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_to_user', to='book_review.User'),
        ),
    ]
